-- Telaris database schema (PostgreSQL 14+).
-- Used by admin/setup.php. Keep in sync with inc/db.php (project_info, constellations, user_constellations).
--
-- Migration notes (MySQL -> PostgreSQL, ROADMAP ^pg-migration):
--   * Tables are ordered so every FOREIGN KEY target is created before its referrer
--     (Postgres requires the referenced table to exist; there is no global
--     FOREIGN_KEY_CHECKS=0 toggle).
--   * Indexes and UNIQUE constraints are separate CREATE [UNIQUE] INDEX IF NOT EXISTS
--     statements so admin/setup.php's naive ";"-splitter can run each one and re-running
--     setup is idempotent.
--   * No functions, triggers, or expression indexes live here: the ";"-splitter cannot
--     parse a "$$" function body. The shared set_updated_at() trigger function, the
--     immutable_unaccent() wrapper, the per-table updated_at triggers, and the
--     accent+case-insensitive keyword unique index are all created from db.php helpers
--     (db_ensure_pg_prerequisites / db_ensure_updated_at_triggers / the keyword ensure)
--     which exec a whole block at once. setup.php calls them around this load.
--   * AUTO_INCREMENT -> GENERATED BY DEFAULT AS IDENTITY (BY DEFAULT so a data load can
--     insert existing ids and the id=0 default constellation can be inserted explicitly).
--   * ENUM -> VARCHAR + CHECK (federation/app vocab churns; native enums make ALTER
--     TYPE ADD VALUE a same-transaction footgun).

-- Table for users
CREATE TABLE IF NOT EXISTS users (
    id VARCHAR(255) PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NULL DEFAULT NULL, -- NULL = no password yet (unvetted self-enrolled editor, magic-link login only)
    firstname VARCHAR(100) NOT NULL,
    lastname VARCHAR(100) NULL DEFAULT NULL,
    pronouns VARCHAR(255) NULL DEFAULT NULL, -- JSON array of up to 3 strings, e.g. ["they/them","elle"]; NULL = not provided
    type INT NOT NULL DEFAULT 0,
    vetted SMALLINT NOT NULL DEFAULT 1, -- 0 = self-enrolled, not yet vetted by an admin; trust+convenience gate, not an edit gate
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    date_last_login TIMESTAMP NULL DEFAULT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS unique_email ON users (email);
CREATE INDEX IF NOT EXISTS idx_type ON users (type);
CREATE INDEX IF NOT EXISTS idx_date_created ON users (date_created);
CREATE INDEX IF NOT EXISTS idx_email ON users (email);

-- Table for constellations (id 0 = default, created by setup, cannot be erased)
CREATE TABLE IF NOT EXISTS constellations (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL DEFAULT '',
    tagline VARCHAR(500) NOT NULL DEFAULT '',
    slug VARCHAR(255) NULL UNIQUE,
    theme VARCHAR(50) NOT NULL DEFAULT 'cosmic', -- cosmic, abstract, rectangles, stripes
    import_source VARCHAR(500) NULL DEFAULT NULL,
    tour_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    tour_start_mode VARCHAR(16) NOT NULL DEFAULT 'manual' CHECK (tour_start_mode IN ('immediate','idle','manual')),
    tour_idle_seconds INT NOT NULL DEFAULT 30,
    tour_node_selection VARCHAR(16) NOT NULL DEFAULT 'all' CHECK (tour_node_selection IN ('all','accentuated','random_n','tagged')),
    tour_random_count INT NOT NULL DEFAULT 10,
    tour_default_dwell INT NOT NULL DEFAULT 8,
    tour_loop BOOLEAN NOT NULL DEFAULT TRUE,
    keyword_chips_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    idle_spotlight_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    idle_spotlight_selection VARCHAR(16) NOT NULL DEFAULT 'all' CHECK (idle_spotlight_selection IN ('all','accentuated')),
    idle_spotlight_idle_seconds INT NOT NULL DEFAULT 30,
    related_nodes_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    show_2d_view BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255) NULL DEFAULT NULL,
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_constellations_created_by ON constellations (created_by);

-- Table for keywords
CREATE TABLE IF NOT EXISTS keywords (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    constellation_id INT NOT NULL DEFAULT 0,
    keyword VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255) NULL DEFAULT NULL,
    FOREIGN KEY (constellation_id) REFERENCES constellations(id),
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
);
-- NOTE: the accent+case-insensitive UNIQUE on (keyword, constellation_id) is an
-- expression index on lower(immutable_unaccent(keyword)) and is created by
-- db_ensure_keywords_unaccent_index() (it needs the immutable_unaccent function and
-- the unaccent extension, neither of which can live in this splittable file).
CREATE INDEX IF NOT EXISTS idx_keyword ON keywords (keyword);
CREATE INDEX IF NOT EXISTS idx_keywords_constellation_id ON keywords (constellation_id);
CREATE INDEX IF NOT EXISTS idx_keywords_created_by ON keywords (created_by);

-- Wormholes (nodes).
CREATE TABLE IF NOT EXISTS nodes (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    constellation_id INT NOT NULL DEFAULT 0,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    url VARCHAR(500) NULL,
    image_url VARCHAR(500) NULL,
    image_attribution VARCHAR(255) NULL,
    icon_url VARCHAR(500) NULL,
    embed_code TEXT NULL,
    audio_url VARCHAR(500) NULL,
    audio_autoplay BOOLEAN NOT NULL DEFAULT TRUE,
    audio_loop BOOLEAN NOT NULL DEFAULT FALSE,
    video_url VARCHAR(500) NULL,
    video_autoplay BOOLEAN NOT NULL DEFAULT TRUE,
    node_type VARCHAR(16) NOT NULL DEFAULT 'object' CHECK (node_type IN ('object','portal')),
    target_constellation_id INT NULL,
    is_accentuated BOOLEAN NOT NULL DEFAULT FALSE,
    show_keywords BOOLEAN NOT NULL DEFAULT FALSE,
    use_image_as_node BOOLEAN NOT NULL DEFAULT FALSE,
    source_facet VARCHAR(255) NULL,
    media_type VARCHAR(50) NULL,
    source_created_at VARCHAR(30) NULL,
    import_slug VARCHAR(255) NULL,
    media_mode VARCHAR(16) NOT NULL DEFAULT 'classic',
    hotglue_page VARCHAR(255) NULL DEFAULT NULL,
    created_by VARCHAR(255) NULL,
    animation JSONB NOT NULL DEFAULT '{"radius":5.0,"theta":0,"phi":0,"speed":0.0025,"phase":0}'::jsonb,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (constellation_id) REFERENCES constellations(id),
    FOREIGN KEY (target_constellation_id) REFERENCES constellations(id) ON DELETE SET NULL,
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_nodes_constellation_id ON nodes (constellation_id);
CREATE INDEX IF NOT EXISTS idx_target_constellation_id ON nodes (target_constellation_id);
CREATE INDEX IF NOT EXISTS idx_nodes_created_by ON nodes (created_by);
CREATE INDEX IF NOT EXISTS idx_import_slug ON nodes (constellation_id, import_slug);

-- First-login consent records (BACKLOG ^consent-gate-first-login). One row per
-- (user, document, accepted version); history preserved across version bumps.
CREATE TABLE IF NOT EXISTS user_consents (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    document_type VARCHAR(32) NOT NULL,    -- 'tos' | 'privacy'
    document_version VARCHAR(32) NOT NULL,
    consented_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS uniq_user_doc_version ON user_consents (user_id, document_type, document_version);
CREATE INDEX IF NOT EXISTS idx_user_consents_user ON user_consents (user_id);

-- Operator decision per document version for the "documents changed" alert.
CREATE TABLE IF NOT EXISTS consent_notice_decisions (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_type VARCHAR(32) NOT NULL,    -- 'tos' | 'privacy'
    document_version VARCHAR(32) NOT NULL,
    decision VARCHAR(16) NOT NULL,         -- 'sent' | 'disregarded'
    decided_by VARCHAR(255) NULL,          -- admin user id (no FK; audit kept if admin deleted)
    decided_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uniq_doc_version ON consent_notice_decisions (document_type, document_version);

-- One row per editor actually emailed about a document version, so a re-send
-- never double-notifies. Cascades away with the user.
CREATE TABLE IF NOT EXISTS consent_notifications (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    document_type VARCHAR(32) NOT NULL,
    document_version VARCHAR(32) NOT NULL,
    notified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS uniq_notif_user_doc_version ON consent_notifications (user_id, document_type, document_version);
CREATE INDEX IF NOT EXISTS idx_consent_notifications_user ON consent_notifications (user_id);

-- Junction: galaxies that tour by tag pick visitable nodes from these keywords (OR logic).
CREATE TABLE IF NOT EXISTS constellation_tour_keywords (
    constellation_id INT NOT NULL,
    keyword_id INT NOT NULL,
    PRIMARY KEY (constellation_id, keyword_id),
    FOREIGN KEY (constellation_id) REFERENCES constellations(id) ON DELETE CASCADE,
    FOREIGN KEY (keyword_id) REFERENCES keywords(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_ctk_constellation_id ON constellation_tour_keywords (constellation_id);
CREATE INDEX IF NOT EXISTS idx_ctk_keyword_id ON constellation_tour_keywords (keyword_id);

-- Standalone hotglue pages: freeform hotglue canvases with their own identity,
-- optionally assigned to a wormhole. slug is the hg/content/<slug> dir name
-- ("page-<id>" for editor-created, "node-<id>" for legacy per-wormhole pages).
CREATE TABLE IF NOT EXISTS hotglue_pages (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(255) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL DEFAULT '',
    owner_user_id VARCHAR(255) NULL DEFAULT NULL,
    node_id INT NULL DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_hotglue_pages_node FOREIGN KEY (node_id) REFERENCES nodes(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_hotglue_pages_owner ON hotglue_pages (owner_user_id);
CREATE INDEX IF NOT EXISTS idx_hotglue_pages_node ON hotglue_pages (node_id);

-- Junction table for node-keyword relationships (many-to-many).
-- `created_by` attributes who tagged this wormhole with this keyword -- distinct
-- from `keywords.created_by`, which records who first created the keyword itself.
CREATE TABLE IF NOT EXISTS node_keywords (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_id INT NOT NULL,
    keyword_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255) NULL DEFAULT NULL,
    FOREIGN KEY (node_id) REFERENCES nodes(id) ON DELETE CASCADE,
    FOREIGN KEY (keyword_id) REFERENCES keywords(id) ON DELETE CASCADE,
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS unique_node_keyword ON node_keywords (node_id, keyword_id);
CREATE INDEX IF NOT EXISTS idx_nk_node_id ON node_keywords (node_id);
CREATE INDEX IF NOT EXISTS idx_nk_keyword_id ON node_keywords (keyword_id);
CREATE INDEX IF NOT EXISTS idx_node_keywords_created_by ON node_keywords (created_by);

-- Table for project information (one row per locale: en, es, pt, fr).
CREATE TABLE IF NOT EXISTS project_info (
    locale VARCHAR(10) NOT NULL PRIMARY KEY,
    name VARCHAR(2000) NOT NULL DEFAULT '',
    description VARCHAR(2000) NOT NULL DEFAULT '',
    iframe_back_text VARCHAR(2000) NOT NULL DEFAULT '',
    alert_message VARCHAR(2000) NOT NULL DEFAULT '',
    edit_button_text VARCHAR(200) NOT NULL DEFAULT 'Edit',
    loading_text VARCHAR(200) NOT NULL DEFAULT 'Loading',
    back_button_text VARCHAR(200) NOT NULL DEFAULT 'Back',
    system_online_text VARCHAR(200) NOT NULL DEFAULT 'System: Online',
    reload_system_text VARCHAR(200) NOT NULL DEFAULT 'Reload System',
    scan_system_text VARCHAR(200) NOT NULL DEFAULT 'SCAN SYSTEM...',
    clear_scan_text VARCHAR(200) NOT NULL DEFAULT 'Clear Scan',
    systems_label_text VARCHAR(200) NOT NULL DEFAULT 'Systems:',
    hyperlinks_label_text VARCHAR(200) NOT NULL DEFAULT 'Hyperlinks:',
    initialize_auth_text VARCHAR(200) NOT NULL DEFAULT 'Initialize Auth',
    admin_label_text VARCHAR(200) NOT NULL DEFAULT 'Admin',
    logout_label_text VARCHAR(200) NOT NULL DEFAULT 'Logout',
    click_to_view_text VARCHAR(200) NOT NULL DEFAULT 'Click to view',
    tap_to_view_text VARCHAR(200) NOT NULL DEFAULT 'Tap again to view',
    open_portal_text VARCHAR(200) NOT NULL DEFAULT 'Open the Portal',
    default_constellation_id INT NOT NULL DEFAULT 0
);

-- Table for editor constellation access (user_id = users.id, constellation_id = constellations.id). Admins see all; editors see only rows here.
CREATE TABLE IF NOT EXISTS user_constellations (
    user_id VARCHAR(255) NOT NULL,
    constellation_id INT NOT NULL,
    access_level VARCHAR(16) NOT NULL DEFAULT 'read_write' CHECK (access_level IN ('read_write','read_only')), -- read_only = editor may list/open but not mutate this galaxy's components
    PRIMARY KEY (user_id, constellation_id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (constellation_id) REFERENCES constellations(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_uc_user_id ON user_constellations (user_id);
CREATE INDEX IF NOT EXISTS idx_uc_constellation_id ON user_constellations (constellation_id);

-- Single-use, emailed-link login tokens (editor self-enrollment). One table for
-- several purposes (magic_login, enroll_confirm, vetting); 64-hex token stored
-- SHA-256-hashed; expires_at computed in PHP (UTC). Created lazily by
-- db_ensure_login_tokens_table(); mirrored here for fresh installs.
CREATE TABLE IF NOT EXISTS login_tokens (
    token_hash CHAR(64) NOT NULL PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    purpose VARCHAR(24) NOT NULL,          -- 'magic_login' | 'enroll_confirm' | 'vetting'
    expires_at TIMESTAMP NOT NULL,
    used_at TIMESTAMP NULL DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_login_tokens_user_purpose ON login_tokens (user_id, purpose);
CREATE INDEX IF NOT EXISTS idx_login_tokens_expires_at ON login_tokens (expires_at);

-- Table for API keys
CREATE TABLE IF NOT EXISTS api_keys (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    api_key VARCHAR(64) NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_used_at TIMESTAMP NULL DEFAULT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE UNIQUE INDEX IF NOT EXISTS unique_api_key ON api_keys (api_key);
CREATE INDEX IF NOT EXISTS idx_is_active ON api_keys (is_active);

-- Table for local snapshots (full system backups stored on disk).
-- Excluded from backup dumps (instance-local state).
CREATE TABLE IF NOT EXISTS snapshots (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filename VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    size_bytes BIGINT NOT NULL DEFAULT 0,
    created_by VARCHAR(255) NULL,
    trigger_type VARCHAR(16) NOT NULL DEFAULT 'manual' CHECK (trigger_type IN ('manual','scheduled')),
    note VARCHAR(500) NULL,
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS unique_filename ON snapshots (filename);
CREATE INDEX IF NOT EXISTS idx_snapshots_created_at ON snapshots (created_at);
CREATE INDEX IF NOT EXISTS idx_snapshots_created_by ON snapshots (created_by);

-- Schedule for automatic snapshots (single row, id=1).
-- Excluded from backup dumps (instance-local state).
CREATE TABLE IF NOT EXISTS snapshot_schedule (
    id SMALLINT NOT NULL PRIMARY KEY DEFAULT 1,
    enabled BOOLEAN NOT NULL DEFAULT FALSE,
    hour SMALLINT NOT NULL DEFAULT 3,
    keep_days INT NOT NULL DEFAULT 7,
    last_run_at TIMESTAMP NULL DEFAULT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
