<?php
declare(strict_types=1);

use PHPUnit\Framework\TestCase;

/**
 * Create-read-update-delete round-trip for a galaxy (constellation), plus the
 * duplicate-detection and cascade-delete contracts, asserted through the public
 * db_* helpers.
 *
 * The cascade test is the high-value one: db_delete_constellation tears down the
 * galaxy's nodes, their keyword junctions, and the keywords in a single
 * transaction. That fan-out is the kind of thing a schema migration can quietly
 * break (a missing ON DELETE rule, a transaction that does not roll back as a
 * unit). Asserting it through the helpers means the contract is pinned
 * independent of engine, and survives the planned MySQL to PostgreSQL migration
 * (ROADMAP ^pg-migration) unchanged.
 *
 * The slug / name duplicate checks guard the user-facing "a galaxy with this
 * name already exists" path; if the underlying uniqueness or lookup drifts,
 * editors would either hit a hard DB error or silently create collisions.
 *
 * Fixtures: ephemeral rows torn down by id (never by name).
 */
final class ConstellationCrudRoundTripTest extends TestCase
{
    /** @var list<int> */
    private array $cids = [];

    protected function tearDown(): void
    {
        $pdo = getDB();
        foreach ($this->cids as $cid) {
            $pdo->prepare("DELETE FROM node_keywords WHERE node_id IN (SELECT id FROM nodes WHERE constellation_id = :c)")->execute([':c' => $cid]);
            $pdo->prepare("DELETE FROM nodes WHERE constellation_id = :c")->execute([':c' => $cid]);
            $pdo->prepare("DELETE FROM keywords WHERE constellation_id = :c")->execute([':c' => $cid]);
            $pdo->prepare("DELETE FROM constellations WHERE id = :c")->execute([':c' => $cid]);
        }
        $this->cids = [];
    }

    private function track(int $cid): int
    {
        $this->cids[] = $cid;
        return $cid;
    }

    /* ---- create + read ------------------------------------------------- */

    public function testCreateAndGetById(): void
    {
        $sfx = bin2hex(random_bytes(4));
        $cid = $this->track(db_create_constellation('Galaxy ' . $sfx, 'a tagline', 'gx-' . $sfx, 'cosmic'));

        $row = db_get_constellation_by_id($cid);
        $this->assertNotNull($row);
        $this->assertSame('Galaxy ' . $sfx, $row['name']);
        $this->assertSame('a tagline', $row['tagline']);
        $this->assertSame('gx-' . $sfx, $row['slug']);
        $this->assertSame('cosmic', $row['theme']);
    }

    public function testGetBySlugReturnsTheSameRow(): void
    {
        $sfx = bin2hex(random_bytes(4));
        $slug = 'gxslug-' . $sfx;
        $cid = $this->track(db_create_constellation('Slug galaxy ' . $sfx, '', $slug, 'cosmic'));

        $row = db_get_constellation_by_slug($slug);
        $this->assertNotNull($row);
        $this->assertSame($cid, $row['id']);
        $this->assertSame('Slug galaxy ' . $sfx, $row['name']);
    }

    public function testSlugAutoGeneratedFromName(): void
    {
        $sfx = bin2hex(random_bytes(4));
        $name = 'Auto Slug ' . $sfx;
        $cid = $this->track(db_create_constellation($name)); // no slug passed

        $row = db_get_constellation_by_id($cid);
        $this->assertSame(db_slugify($name), $row['slug']);
    }

    public function testGetByIdReturnsNullForMissing(): void
    {
        $this->assertNull(db_get_constellation_by_id(2000000000));
    }

    /* ---- duplicate detection ------------------------------------------- */

    public function testExistsDetectsNameAndSlug(): void
    {
        $sfx = bin2hex(random_bytes(4));
        $name = 'Dupe ' . $sfx;
        $slug = 'dupe-' . $sfx;
        $cid = $this->track(db_create_constellation($name, '', $slug, 'cosmic'));

        $hit = db_constellation_exists($name, $slug);
        $this->assertTrue($hit['name']);
        $this->assertTrue($hit['slug']);

        // Excluding the row itself, it is no longer a duplicate (the edit path).
        $self = db_constellation_exists($name, $slug, $cid);
        $this->assertFalse($self['name']);
        $this->assertFalse($self['slug']);

        // A name/slug nobody uses is not a duplicate.
        $miss = db_constellation_exists('Nonexistent ' . $sfx, 'nope-' . $sfx);
        $this->assertFalse($miss['name']);
        $this->assertFalse($miss['slug']);
    }

    /* ---- update -------------------------------------------------------- */

    public function testUpdateRoundTrip(): void
    {
        $sfx = bin2hex(random_bytes(4));
        $cid = $this->track(db_create_constellation('Before ' . $sfx, 'old tag', 'upd-' . $sfx, 'cosmic'));

        db_update_constellation($cid, 'After ' . $sfx, 'new tag', 'upd2-' . $sfx, 'abstract');

        $row = db_get_constellation_by_id($cid);
        $this->assertSame('After ' . $sfx, $row['name']);
        $this->assertSame('new tag', $row['tagline']);
        $this->assertSame('upd2-' . $sfx, $row['slug']);
        $this->assertSame('abstract', $row['theme']);
    }

    /* ---- delete + cascade ---------------------------------------------- */

    public function testDeleteCascadesToNodesAndKeywords(): void
    {
        $sfx = bin2hex(random_bytes(4));
        $cid = $this->track(db_create_constellation('Cascade ' . $sfx, '', 'casc-' . $sfx, 'cosmic'));
        $nodeId = db_create_node('cascade node', null, null, '{}', $cid);
        db_save_node_keywords($nodeId, ['alpha', 'beta']);

        // Preconditions: the node, its keyword junctions, and the keyword rows exist.
        $this->assertNotNull(db_get_node_by_id($nodeId));
        $this->assertCount(2, db_get_keywords_for_node($nodeId));
        $this->assertCount(2, db_get_keywords_for_constellation($cid));

        db_delete_constellation($cid);

        // Everything is gone, through the same helper lenses.
        $this->assertNull(db_get_node_by_id($nodeId), 'nodes must be removed with their galaxy');
        $this->assertNull(db_get_constellation_by_id($cid), 'the galaxy itself must be gone');
        $this->assertSame([], db_get_keywords_for_node($nodeId), 'keyword junctions must be gone');
        $this->assertCount(0, db_get_keywords_for_constellation($cid), 'keywords must be removed with their galaxy');
    }

    public function testDefaultConstellationCannotBeDeleted(): void
    {
        $defaultId = db_get_default_constellation_id();
        $this->expectException(InvalidArgumentException::class);
        db_delete_constellation($defaultId);
    }
}
